[changelog]
header = "# Changelog"
footer = ""

body = """
{% for group, commits in commits | group_by(attribute="group") %}
## [{{version}}] - {{timestamp}}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/edgexfoundry/edgex-go/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""

[commit]
message_filters = [
    { pattern = "^feat", group = "ğŸš€ Features" },
    { pattern = "^fix", group = "ğŸ› Bug Fixes" },
    { pattern = "^chore", group = "ğŸ›  Maintenance" },
    { pattern = "^docs", group = "ğŸ“– Documentation" },
    { pattern = "^test", group = "ğŸ§ª Testing" },
    { pattern = "^refactor", group = "ğŸ”¨ Refactoring" }
]

[git]
topo_order = true
merge = true
